// Generated by scripts/build_sfx.py: where each clip sits in beyblade.mp3, in samples.
export const SPRITE_RATE = 44100;
/** MP3 decoders add a varying delay, so the decoded file is realigned on its first sample louder than this. */
export const ALIGN_LEVEL = 0.3;
export const FIRST_LOUD_AT = 6792;
export const CLIPS: { name: string; start: number; length: number }[] = [
  { name: "light", start: 6615, length: 11025 },
  { name: "light", start: 24255, length: 11025 },
  { name: "light", start: 41895, length: 11025 },
  { name: "light", start: 59535, length: 11025 },
  { name: "light", start: 77175, length: 11025 },
  { name: "light", start: 94815, length: 11025 },
  { name: "medium", start: 112455, length: 17640 },
  { name: "medium", start: 136710, length: 17640 },
  { name: "medium", start: 160965, length: 17640 },
  { name: "medium", start: 185220, length: 17640 },
  { name: "medium", start: 209475, length: 17640 },
  { name: "medium", start: 233730, length: 17640 },
  { name: "heavy", start: 257985, length: 24255 },
  { name: "heavy", start: 288855, length: 24255 },
  { name: "heavy", start: 319725, length: 24255 },
  { name: "launch", start: 350595, length: 29988 },
  { name: "topple", start: 387198, length: 61739 },
  { name: "spin", start: 455552, length: 132300 },
];
