"""
Cuts the recorded sound effects out of real Beyblade X recordings and packs them into one
audio sprite, src/game/sfx/beyblade.mp3, plus the table of where each clip sits in it,
src/game/sfx/clips.ts.

Source: the "Beyblade" pack by Sadiquecat on Freesound (CC0), https://freesound.org/people/Sadiquecat/packs/41654/
Put the HQ previews in one folder as <id>.mp3 (e.g. https://cdn.freesound.org/previews/794/794837_5287430-hq.mp3)
and run:  python scripts/build_sfx.py <that folder>

Needs numpy, scipy and soundfile (libsndfile 1.1+ for MP3).
"""

import sys
from pathlib import Path

import numpy as np
import soundfile as sf
from scipy.signal import resample_poly

RATE = 44100
GAP = 0.15  # silence between clips, so decoder padding never clips into one
ALIGN_LEVEL = 0.3
ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "src" / "game" / "sfx"

# (name, recording, approximate time of the hit in seconds, clip length in seconds)
HITS = [
    ("light", "794837", 4.54, 0.25),
    ("light", "794837", 5.75, 0.25),
    ("light", "794837", 9.73, 0.25),
    ("light", "794837", 10.54, 0.25),
    ("light", "794834", 29.66, 0.25),
    ("light", "794834", 32.74, 0.25),
    ("medium", "794837", 2.46, 0.4),
    ("medium", "794837", 3.1, 0.4),
    ("medium", "794837", 3.7, 0.4),
    ("medium", "794837", 7.48, 0.4),
    ("medium", "794837", 9.01, 0.4),
    ("medium", "794837", 11.78, 0.4),
    ("heavy", "794834", 23.1, 0.55),
    ("heavy", "794834", 24.64, 0.55),
    ("heavy", "794834", 26.16, 0.55),
]
# (name, recording, start, end): taken as-is rather than aligned to a hit.
SPANS = [
    ("launch", "794832", 0.12, 0.8),
    ("topple", "794843", 37.9, 39.3),
]
LOOP = ("spin", "794843", 19.0, 3.0, 0.3)  # name, recording, start, loop length, crossfade


def load(folder: Path, rec: str, cache={}):
    if rec not in cache:
        x, sr = sf.read(folder / f"{rec}.mp3")
        if x.ndim > 1:
            x = x.mean(axis=1)
        cache[rec] = resample_poly(x, RATE, sr) if sr != RATE else x
    return cache[rec]


def fade(clip: np.ndarray, fade_in=0.003, fade_out_frac=0.4) -> np.ndarray:
    clip = clip.copy()
    n_in = int(fade_in * RATE)
    clip[:n_in] *= np.linspace(0, 1, n_in)
    n_out = int(len(clip) * fade_out_frac)
    clip[-n_out:] *= 0.5 * (1 + np.cos(np.linspace(0, np.pi, n_out)))
    return clip


def peak_normalise(clip: np.ndarray, peak=0.9) -> np.ndarray:
    return clip * (peak / np.abs(clip).max())


def cut_hit(x: np.ndarray, t: float, length: float) -> np.ndarray:
    """Finds the hit's true onset near t, and cuts from just before it."""
    a, b = int((t - 0.1) * RATE), int((t + 0.1) * RATE)
    peak = a + int(np.argmax(np.abs(x[a:b])))
    level = np.abs(x[peak])
    look = int(0.03 * RATE)
    above = np.nonzero(np.abs(x[peak - look : peak]) > 0.1 * level)[0]
    onset = peak - look + (above[0] if len(above) else look)
    start = onset - int(0.004 * RATE)
    return peak_normalise(fade(x[start : start + int(length * RATE)]))


def make_loop(x: np.ndarray, start: float, length: float, xfade: float) -> np.ndarray:
    """A loop that joins seamlessly: its tail is crossfaded (equal power) into its head."""
    a, n, m = int(start * RATE), int(length * RATE), int(xfade * RATE)
    seg = x[a : a + n + m].copy()
    out = seg[:n].copy()
    ramp = np.linspace(0, np.pi / 2, m)
    out[:m] = seg[:m] * np.sin(ramp) + seg[n : n + m] * np.cos(ramp)
    rms = np.sqrt((out**2).mean())
    return out * (0.12 / rms)


def main(folder: Path):
    clips: list[tuple[str, np.ndarray]] = []
    for name, rec, t, length in HITS:
        clips.append((name, cut_hit(load(folder, rec), t, length)))
    for name, rec, a, b in SPANS:
        x = load(folder, rec)
        clips.append((name, peak_normalise(fade(x[int(a * RATE) : int(b * RATE)], fade_out_frac=0.2))))
    name, rec, start, length, xfade = LOOP
    clips.append((name, make_loop(load(folder, rec), start, length, xfade)))

    gap = np.zeros(int(GAP * RATE))
    parts, table, pos = [gap], [], len(gap)
    for name, clip in clips:
        table.append((name, pos, len(clip)))
        parts += [clip, gap]
        pos += len(clip) + len(gap)
    sprite = np.clip(np.concatenate(parts), -1, 1)
    first_loud = int(np.argmax(np.abs(sprite) > ALIGN_LEVEL))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    sf.write(OUT_DIR / "beyblade.mp3", sprite, RATE, format="MP3")
    lines = [
        "// Generated by scripts/build_sfx.py: where each clip sits in beyblade.mp3, in samples.",
        f"export const SPRITE_RATE = {RATE};",
        "/** MP3 decoders add a varying delay, so the decoded file is realigned on its first sample louder than this. */",
        f"export const ALIGN_LEVEL = {ALIGN_LEVEL};",
        f"export const FIRST_LOUD_AT = {first_loud};",
        "export const CLIPS: { name: string; start: number; length: number }[] = [",
        *[f'  {{ name: "{n}", start: {s}, length: {l} }},' for n, s, l in table],
        "];",
        "",
    ]
    (OUT_DIR / "clips.ts").write_text("\n".join(lines), encoding="utf-8")
    size = (OUT_DIR / "beyblade.mp3").stat().st_size
    print(f"{len(table)} clips, {len(sprite) / RATE:.1f}s, {size / 1024:.0f} KB")


if __name__ == "__main__":
    main(Path(sys.argv[1]))
